url: http://handshake-mentoring.github.io
baseurl: 

# Site settings
title: handshake
logo: logo.png
email: carinaboo@berkeley.edu
description: "Mentoring platform for college students seeking career advice and interview help from engineers, designers, and managers in the tech industry."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: ef5a34 # fed136
  secondary: ff7a0b # fec503 
  primary-dark: 222 # 283173
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Carina Boo
  pic: carina
  position: 
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/carinaboo
    - title: github
      url: https://github.com/carinaboo
    - title: link
      url: http://carinaboo.com/

- name: Arezu Aghaseyedjavadi
  pic: arezu
  position: 
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/arezua
    - title: github
      url: https://github.com/arezu

- name: Isabelle Angieri
  pic: isabelle
  position: 
  social:
    - title: linkedin
      url: http://www.linkedin.com/pub/isabelle-angieri/17/26a/27a/en
    - title: link
      url: http://isabelleangieri.com/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/handshake.mentoring
  - title: envelope
    url: handshake.mentoring@gmail.com

# Postal address (add as many lines as necessary)
address:
  - line: Hearst Ave
  - line: Berkeley, CA 94709

# Build settings
markdown: kramdown
permalink: pretty